### ISSUE TITLE
Links spanning full satellites

### ISSUE THREAD

**Issue by AlphaOrange** [AlphaOrange/Orbitlist#15]
Satellites that link to another site should be completely link-sensitive. That's hard to manage at the moment since wrapping the whole li into a tag will break orbitlist algorithm.
Maybe some easy solution? Otherwise orbitlist should overwrite click event when link inside the satellite.

**Comment by aloisdg** [comment]
I have a kind of solution for this using CSS.

```css

a {
    color: inherit;
    text-decoration: inherit;
}

.orbit li {
    padding: 0;
}

.orbit li a {
    margin: 0;
    display: block;
    width: 100%;
    height: 100%;
}

.orbit li,
.orbit li a {
    text-align: center;
    line-height: 60px;
}

```

And the HTML

```html
<li>
    <a href="https://github.com/AlphaOrange/Orbitlist/issues" title="yolo">test</a>
</li>
```

I would be glad to submit a PR, if you like the solution (and you add a license 😉 ).
